export const CATEGORIES = [
  'Food & Drink',
  'Accommodation',
  'Flights',
  'Transport',
  'Activities',
  'Entertainment',
  'Shopping',
  'Groceries',
  'Car Rental',
  'Health & Medical',
  'Travel Insurance',
  'Visa & Fees',
  'Utilities',
  'Other',
];

export const CAT_ICONS = {
  'Food & Drink':     '🍽',
  'Accommodation':    '🏨',
  'Flights':          '✈️',
  'Transport':        '🚗',
  'Activities':       '🎯',
  'Entertainment':    '🎉',
  'Shopping':         '🛍',
  'Groceries':        '🛒',
  'Car Rental':       '🚘',
  'Health & Medical': '🏥',
  'Travel Insurance': '🛡',
  'Visa & Fees':      '📋',
  'Utilities':        '💡',
  'Other':            '📌',
  'Settlement':       '💸',
};
