/**
 * Complete ISO 4217 active currency list.
 * Each entry: { code, symbol, name }
 * Sorted alphabetically by name.
 */
export const CURRENCIES = [
  { code: 'AFN', symbol: '؋',    name: 'Afghan Afghani' },
  { code: 'ALL', symbol: 'L',    name: 'Albanian Lek' },
  { code: 'DZD', symbol: 'دج',   name: 'Algerian Dinar' },
  { code: 'AOA', symbol: 'Kz',   name: 'Angolan Kwanza' },
  { code: 'ARS', symbol: '$',    name: 'Argentine Peso' },
  { code: 'AMD', symbol: '֏',    name: 'Armenian Dram' },
  { code: 'AWG', symbol: 'ƒ',    name: 'Aruban Florin' },
  { code: 'AUD', symbol: 'A$',   name: 'Australian Dollar' },
  { code: 'AZN', symbol: '₼',    name: 'Azerbaijani Manat' },
  { code: 'BSD', symbol: 'B$',   name: 'Bahamian Dollar' },
  { code: 'BHD', symbol: 'BD',   name: 'Bahraini Dinar' },
  { code: 'BDT', symbol: '৳',    name: 'Bangladeshi Taka' },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar' },
  { code: 'BYN', symbol: 'Br',   name: 'Belarusian Ruble' },
  { code: 'BZD', symbol: 'BZ$',  name: 'Belize Dollar' },
  { code: 'XOF', symbol: 'Fr',   name: 'West African CFA Franc' },
  { code: 'BMD', symbol: '$',    name: 'Bermudian Dollar' },
  { code: 'BTN', symbol: 'Nu',   name: 'Bhutanese Ngultrum' },
  { code: 'BOB', symbol: 'Bs',   name: 'Bolivian Boliviano' },
  { code: 'BAM', symbol: 'KM',   name: 'Bosnia-Herzegovina Convertible Mark' },
  { code: 'BWP', symbol: 'P',    name: 'Botswanan Pula' },
  { code: 'BRL', symbol: 'R$',   name: 'Brazilian Real' },
  { code: 'GBP', symbol: '£',    name: 'British Pound' },
  { code: 'BND', symbol: 'B$',   name: 'Brunei Dollar' },
  { code: 'BGN', symbol: 'лв',   name: 'Bulgarian Lev' },
  { code: 'BIF', symbol: 'Fr',   name: 'Burundian Franc' },
  { code: 'KHR', symbol: '៛',    name: 'Cambodian Riel' },
  { code: 'CAD', symbol: 'CA$',  name: 'Canadian Dollar' },
  { code: 'CVE', symbol: 'Esc',  name: 'Cape Verdean Escudo' },
  { code: 'KYD', symbol: '$',    name: 'Cayman Islands Dollar' },
  { code: 'XAF', symbol: 'Fr',   name: 'Central African CFA Franc' },
  { code: 'CLP', symbol: '$',    name: 'Chilean Peso' },
  { code: 'CNY', symbol: '¥',    name: 'Chinese Yuan' },
  { code: 'COP', symbol: '$',    name: 'Colombian Peso' },
  { code: 'KMF', symbol: 'Fr',   name: 'Comorian Franc' },
  { code: 'CDF', symbol: 'Fr',   name: 'Congolese Franc' },
  { code: 'CRC', symbol: '₡',    name: 'Costa Rican Colón' },
  { code: 'HRK', symbol: 'kn',   name: 'Croatian Kuna' },
  { code: 'CUP', symbol: '$',    name: 'Cuban Peso' },
  { code: 'CZK', symbol: 'Kč',   name: 'Czech Koruna' },
  { code: 'DKK', symbol: 'kr',   name: 'Danish Krone' },
  { code: 'DJF', symbol: 'Fr',   name: 'Djiboutian Franc' },
  { code: 'DOP', symbol: '$',    name: 'Dominican Peso' },
  { code: 'XCD', symbol: '$',    name: 'East Caribbean Dollar' },
  { code: 'EGP', symbol: '£',    name: 'Egyptian Pound' },
  { code: 'ERN', symbol: 'Nfk',  name: 'Eritrean Nakfa' },
  { code: 'ETB', symbol: 'Br',   name: 'Ethiopian Birr' },
  { code: 'EUR', symbol: '€',    name: 'Euro' },
  { code: 'FJD', symbol: '$',    name: 'Fijian Dollar' },
  { code: 'GMD', symbol: 'D',    name: 'Gambian Dalasi' },
  { code: 'GEL', symbol: '₾',    name: 'Georgian Lari' },
  { code: 'GHS', symbol: '₵',    name: 'Ghanaian Cedi' },
  { code: 'GIP', symbol: '£',    name: 'Gibraltar Pound' },
  { code: 'GTQ', symbol: 'Q',    name: 'Guatemalan Quetzal' },
  { code: 'GNF', symbol: 'Fr',   name: 'Guinean Franc' },
  { code: 'GYD', symbol: '$',    name: 'Guyanese Dollar' },
  { code: 'HTG', symbol: 'G',    name: 'Haitian Gourde' },
  { code: 'HNL', symbol: 'L',    name: 'Honduran Lempira' },
  { code: 'HKD', symbol: 'HK$',  name: 'Hong Kong Dollar' },
  { code: 'HUF', symbol: 'Ft',   name: 'Hungarian Forint' },
  { code: 'ISK', symbol: 'kr',   name: 'Icelandic Króna' },
  { code: 'INR', symbol: '₹',    name: 'Indian Rupee' },
  { code: 'IDR', symbol: 'Rp',   name: 'Indonesian Rupiah' },
  { code: 'IRR', symbol: '﷼',   name: 'Iranian Rial' },
  { code: 'IQD', symbol: 'ع.د',  name: 'Iraqi Dinar' },
  { code: 'ILS', symbol: '₪',    name: 'Israeli New Shekel' },
  { code: 'JMD', symbol: '$',    name: 'Jamaican Dollar' },
  { code: 'JPY', symbol: '¥',    name: 'Japanese Yen' },
  { code: 'JOD', symbol: 'JD',   name: 'Jordanian Dinar' },
  { code: 'KZT', symbol: '₸',    name: 'Kazakhstani Tenge' },
  { code: 'KES', symbol: 'Ksh',  name: 'Kenyan Shilling' },
  { code: 'KWD', symbol: 'KD',   name: 'Kuwaiti Dinar' },
  { code: 'KGS', symbol: 'с',    name: 'Kyrgyzstani Som' },
  { code: 'LAK', symbol: '₭',    name: 'Lao Kip' },
  { code: 'LBP', symbol: 'L£',   name: 'Lebanese Pound' },
  { code: 'LSL', symbol: 'L',    name: 'Lesotho Loti' },
  { code: 'LRD', symbol: '$',    name: 'Liberian Dollar' },
  { code: 'LYD', symbol: 'LD',   name: 'Libyan Dinar' },
  { code: 'MOP', symbol: 'P',    name: 'Macanese Pataca' },
  { code: 'MKD', symbol: 'ден',  name: 'Macedonian Denar' },
  { code: 'MGA', symbol: 'Ar',   name: 'Malagasy Ariary' },
  { code: 'MWK', symbol: 'MK',   name: 'Malawian Kwacha' },
  { code: 'MYR', symbol: 'RM',   name: 'Malaysian Ringgit' },
  { code: 'MVR', symbol: 'Rf',   name: 'Maldivian Rufiyaa' },
  { code: 'MRU', symbol: 'UM',   name: 'Mauritanian Ouguiya' },
  { code: 'MUR', symbol: '₨',    name: 'Mauritian Rupee' },
  { code: 'MXN', symbol: 'MX$',  name: 'Mexican Peso' },
  { code: 'MDL', symbol: 'L',    name: 'Moldovan Leu' },
  { code: 'MNT', symbol: '₮',    name: 'Mongolian Tögrög' },
  { code: 'MAD', symbol: 'MAD',  name: 'Moroccan Dirham' },
  { code: 'MZN', symbol: 'MT',   name: 'Mozambican Metical' },
  { code: 'MMK', symbol: 'K',    name: 'Myanmar Kyat' },
  { code: 'NAD', symbol: '$',    name: 'Namibian Dollar' },
  { code: 'NPR', symbol: '₨',    name: 'Nepalese Rupee' },
  { code: 'NZD', symbol: 'NZ$',  name: 'New Zealand Dollar' },
  { code: 'NIO', symbol: 'C$',   name: 'Nicaraguan Córdoba' },
  { code: 'NGN', symbol: '₦',    name: 'Nigerian Naira' },
  { code: 'NOK', symbol: 'kr',   name: 'Norwegian Krone' },
  { code: 'OMR', symbol: '﷼',   name: 'Omani Rial' },
  { code: 'PKR', symbol: '₨',    name: 'Pakistani Rupee' },
  { code: 'PAB', symbol: 'B/.',  name: 'Panamanian Balboa' },
  { code: 'PGK', symbol: 'K',    name: 'Papua New Guinean Kina' },
  { code: 'PYG', symbol: '₲',    name: 'Paraguayan Guaraní' },
  { code: 'PEN', symbol: 'S/.',  name: 'Peruvian Sol' },
  { code: 'PHP', symbol: '₱',    name: 'Philippine Peso' },
  { code: 'PLN', symbol: 'zł',   name: 'Polish Złoty' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal' },
  { code: 'RON', symbol: 'lei',  name: 'Romanian Leu' },
  { code: 'RUB', symbol: '₽',    name: 'Russian Ruble' },
  { code: 'RWF', symbol: 'Fr',   name: 'Rwandan Franc' },
  { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal' },
  { code: 'RSD', symbol: 'din',  name: 'Serbian Dinar' },
  { code: 'SCR', symbol: '₨',    name: 'Seychellois Rupee' },
  { code: 'SLE', symbol: 'Le',   name: 'Sierra Leonean Leone' },
  { code: 'SGD', symbol: 'S$',   name: 'Singapore Dollar' },
  { code: 'SBD', symbol: '$',    name: 'Solomon Islands Dollar' },
  { code: 'SOS', symbol: 'Sh',   name: 'Somali Shilling' },
  { code: 'ZAR', symbol: 'R',    name: 'South African Rand' },
  { code: 'SSP', symbol: '£',    name: 'South Sudanese Pound' },
  { code: 'LKR', symbol: '₨',    name: 'Sri Lankan Rupee' },
  { code: 'SDG', symbol: 'ج.س', name: 'Sudanese Pound' },
  { code: 'SRD', symbol: '$',    name: 'Surinamese Dollar' },
  { code: 'SZL', symbol: 'L',    name: 'Swazi Lilangeni' },
  { code: 'SEK', symbol: 'kr',   name: 'Swedish Krona' },
  { code: 'CHF', symbol: 'Fr',   name: 'Swiss Franc' },
  { code: 'SYP', symbol: '£',    name: 'Syrian Pound' },
  { code: 'STN', symbol: 'Db',   name: 'São Tomé & Príncipe Dobra' },
  { code: 'TWD', symbol: 'NT$',  name: 'Taiwan Dollar' },
  { code: 'TJS', symbol: 'SM',   name: 'Tajikistani Somoni' },
  { code: 'TZS', symbol: 'Sh',   name: 'Tanzanian Shilling' },
  { code: 'THB', symbol: '฿',    name: 'Thai Baht' },
  { code: 'TOP', symbol: 'T$',   name: 'Tongan Paʻanga' },
  { code: 'TTD', symbol: 'TT$',  name: 'Trinidad & Tobago Dollar' },
  { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar' },
  { code: 'TRY', symbol: '₺',    name: 'Turkish Lira' },
  { code: 'TMT', symbol: 'T',    name: 'Turkmenistani Manat' },
  { code: 'UGX', symbol: 'Sh',   name: 'Ugandan Shilling' },
  { code: 'UAH', symbol: '₴',    name: 'Ukrainian Hryvnia' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'USD', symbol: '$',    name: 'US Dollar' },
  { code: 'UYU', symbol: '$U',   name: 'Uruguayan Peso' },
  { code: 'UZS', symbol: 'лв',   name: 'Uzbekistani Som' },
  { code: 'VUV', symbol: 'Vt',   name: 'Vanuatu Vatu' },
  { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar' },
  { code: 'VND', symbol: '₫',    name: 'Vietnamese Dong' },
  { code: 'WST', symbol: 'T',    name: 'Samoan Tālā' },
  { code: 'YER', symbol: '﷼',   name: 'Yemeni Rial' },
  { code: 'ZMW', symbol: 'ZK',   name: 'Zambian Kwacha' },
  { code: 'ZWL', symbol: '$',    name: 'Zimbabwean Dollar' },
];

export const DEFAULT_CURRENCY = CURRENCIES.find(c => c.code === 'USD');

/** Quick lookup by code (case-insensitive). */
export function getCurrency(code) {
  return CURRENCIES.find(c => c.code === (code ?? '').toUpperCase()) ?? DEFAULT_CURRENCY;
}
